name: Build APK

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Gradle permission
        run: chmod +x gradlew

      - name: Build Debug APKs
        # Ini bakal build semua flavor yang kita buat tadi
        run: ./gradlew assembleDebug

      - name: Upload All APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          # Path ini mencakup hasil dari kedua flavor
          path: app/build/outputs/apk/**/*.apk
